// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice Railgun RailgunSmartWallet interface (Polygon mainnet).
/// @dev Address: 0x19B620929f97b7b990801496c3b361CA5dEf8C71
///      Only the `shield` function is needed for the ProxyWallet output flow.

interface IRailgunSmartWallet {

    enum TokenType { ERC20, ERC721, ERC1155 }

    struct TokenData {
        TokenType tokenType;  // 0 = ERC20
        address   tokenAddress;
        uint256   tokenSubID; // 0 for ERC20
    }

    /// @param npk   Recipient's Railgun note public key (from Alice's Railgun wallet).
    /// @param token Token data (ERC20 + address + subID=0).
    /// @param value Amount to shield (uint120).
    struct CommitmentPreimage {
        bytes32   npk;
        TokenData token;
        uint120   value;
    }

    /// @param encryptedBundle Poseidon-encrypted note bundle (3×32 bytes).
    ///                        Generated by Alice's Railgun wallet using ephemeral ECDH.
    /// @param shieldKey       Ephemeral public key used for ECDH (32 bytes).
    struct ShieldCiphertext {
        bytes32[3] encryptedBundle;
        bytes32    shieldKey;
    }

    /// @notice Shield ERC-20 tokens into Railgun.
    ///         Caller must have approved this contract via ERC-20.approve().
    ///         After this call, the tokens are held by Railgun and a
    ///         UTXO note is created for `npk` — Alice can privately withdraw.
    /// @param _shieldRequests   Commitment preimages (one per token/recipient).
    /// @param _shieldCiphertext Encrypted note bundles (one per request).
    function shield(
        CommitmentPreimage[] calldata _shieldRequests,
        ShieldCiphertext[]   calldata _shieldCiphertext
    ) external payable;
}
